### ISSUE TITLE
Several servere virus warnings in windows release v0.0.5

### ISSUE THREAD

**Issue by tommienu** [6block/6miner#13]
There is a lot of virus warnings for the 0.0.5 release on windows:
https://www.virustotal.com/gui/file/65aba3df5f54b2d37ce61075eff50ad7db39d41d9f8e6d8fa5813d873f20ef18/detection

Windows Defender flags this as Trojan:Win32/Occamy.C and blocks any installation/run.

Just FYI.

**Comment by codefat-6block** [comment]
it is common for cryptocurrency miner, duplicated with https://github.com/6block/6miner/issues/7
