### ISSUE TITLE
can not run in background

### ISSUE THREAD

**Issue by Baoyx007** [6block/6miner#15]
nohup ./mine_hns.sh &
./mine_hns.sh: 行 10: 29093 段错误               ./6miner -a $ALGO -o $POOL -u $WORKER -p $PWD -m $MODE

**Comment by psteininger** [comment]
@Baoyx007 you should use `screen` like this:
```
screen -S hns ./mine_hns.sh
```
Then you can use `ctrl+a d` to detach, and `screen -r hns` to reattach
