### ISSUE TITLE
Trojan in Windows ZIP

### ISSUE THREAD

**Issue by Onedune** [6block/6miner#19]
Windows defender detect trojan in 6miner-v0.1.0-x64-windows.zip => "Wacatac.C!ml".

**Comment by stevedsp1** [comment]
Same 
Trojan:Win32/Wacatac.C!ml is a computer virus infection that can permit remote attacker to carry out various malicious action on the infected Windows system. With its backdoor resources, makers of Trojan:Win32/Wacatac.C!ml may control the infected computer and do unnecessary actions that causes potential risks to user’s privacy and security.

**Comment by AdamLeyshon** [comment]
Yep, Same here too

**Comment by damajor** [comment]
Still no comment ???

**Comment by codefat-6block** [comment]
dup with #7
