### ISSUE TITLE
WARNING: Virus Total finds 23 trojans!

### ISSUE THREAD

**Issue by E3V3A** [6block/6miner#7]
Are you guys serious?  :angry: 

What the hell is going on here? Are you really trying to push a bunch of trojans to us?
Some of these AV's are the best out there and rarely have false positives. (Microsoft, F-Secure, Fireeye) Please explain youself!

---

![brave_2020-02-10_15-46-55](https://user-images.githubusercontent.com/194392/74156403-eb61b380-4c1e-11ea-9d60-20a5a340d8e7.png)

**Comment by codefat-6block** [comment]
it is common for cryptocurrency miner

**Comment by rallat** [comment]
are you saying that it is common to add trojans to the miners?
