### ISSUE TITLE
Emit hashrate for each GPU

### ISSUE THREAD

**Issue by psteininger** [6block/6miner#9]
It would be great to  have the miner report hashrate for each GPU, like ethminer does for example. 
This would make it easier to package the miner up for HiveOS

**Comment by codefat-6block** [comment]
will provide a http api in the next release

**Comment by psteininger** [comment]
fantastic @codefat-6block. Do you have an ETA for the next release?

**Comment by codefat-6block** [comment]
https://github.com/6block/6miner/releases/tag/v0.1.0
